package org.formulachess.ui;

public interface Settings {
	int BOARD_WIDTH_ORIGIN_INDEX = 0;
	int BOARD_HEIGHT_ORIGIN_INDEX = 1;
	int BOARD_WIDTH_INDEX = 2;
	int BOARD_HEIGHT_INDEX = 3;
	int SQUARE_WIDTH_INDEX = 4;
	int SQUARE_HEIGHT_INDEX = 5;
	int BOARD_WIDTH_DELTA_INDEX = 6;
	int BOARD_HEIGHT_DELTA_INDEX = 7;
	int SWITCH_BUTTON_WIDTH_SIZE_INDEX = 8;
	int SWITCH_BUTTON_HEIGHT_SIZE_INDEX = 9;

	int FONT_SIZE_INDEX = 10;
	int FONT_WIDTH_DELTA_INDEX = 11;
	int FONT_HEIGHT_DELTA_INDEX = 12;
	
	String SET2_PATH = "set2"; //$NON-NLS-1$
	String SET3_PATH = "set3"; //$NON-NLS-1$
	
	int[] SET2 = {
			0,   // BOARD_WIDTH_ORIGIN_INDEX
			0,   // BOARD_HEIGHT_ORIGIN_INDEX
			232, // BOARD_WIDTH_INDEX
			232, // BOARD_HEIGHT_INDEX
			29,  // SQUARE_WIDTH_INDEX
			29,  // SQUARE_HEIGHT_INDEX
			0,   // BOARD_WIDTH_DELTA_INDEX
			0,   // BOARD_HEIGHT_DELTA_INDEX
			30,  // SWITCH_BUTTON_WIDTH_SIZE_INDEX
			30,  // SWITCH_BUTTON_HEIGHT_SIZE_INDEX
			18,   // FONT_SIZE_INDEX,
			10,   // FONT_WIDTH_DELTA_INDEX
			5     // FONT_HEIGHT_DELTA_INDEX
	};
	
	int[] SET3 = {
			0,   // BOARD_WIDTH_ORIGIN_INDEX
			0,   // BOARD_HEIGHT_ORIGIN_INDEX
			384, // BOARD_WIDTH_INDEX
			384, // BOARD_HEIGHT_INDEX
			48,  // SQUARE_WIDTH_INDEX
			48,  // SQUARE_HEIGHT_INDEX
			0,   // BOARD_WIDTH_DELTA_INDEX
			0,   // BOARD_HEIGHT_DELTA_INDEX
			30,  // SWITCH_BUTTON_WIDTH_SIZE_INDEX
			30,  // SWITCH_BUTTON_HEIGHT_SIZE_INDEX
			18,   // FONT_SIZE_INDEX,
			10,   // FONT_WIDTH_DELTA_INDEX
			5     // FONT_HEIGHT_DELTA_INDEX
	};

}
